server:
  port: ${PORT:8080}

spring:
  application:
    name: sanos-salvos-gateway

  cloud:
    gateway:
      routes:
        - id: usuarios-service
          uri: ${USUARIOS_SERVICE_URL:http://localhost:3000}
          predicates:
            - Path=/api/usuarios/**

        - id: mascotas-service
          uri: https://api-gestmascotas-node.onrender.com
          predicates:
            - Path=/api/mascotas/**
          filters:
            - StripPrefix=0
            - FirebaseAuthFilter

        - id: etiquetas-service
          uri: https://api-gestmascotas-node.onrender.com
          predicates:
            - Path=/api/etiquetas/**
          filters:
            - StripPrefix=0
            - FirebaseAuthFilter 

        - id: imagenes-service
          uri: https://api-gestmascotas-node.onrender.com
          predicates:
            - Path=/api/imagenes-mascota/**
          filters:
            - StripPrefix=0
            - FirebaseAuthFilter 

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"

logging:
  level:
    org.springframework.cloud.gateway: DEBUG